### ISSUE TITLE
Client: Issues Page, fix image renders

### ISSUE THREAD

**Issue by kunalkeshan** [kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24#56]
Issues are fetched as markdown and rendered as HTML, the only problem with this is that the images have huge widths.
Fix the image width to avoid overflow after render.

**Comment by kunalkeshan** [comment]
Not only for images but for text as well,

Apply the following properties in the `Typography` parent of the ReactMarkdown component.

```css
  'wordBreak': 'break-word',
  'img': {
    width: '100%',
  }
```
